# Rebind the prefix Ctrl-b to Ctrl-a
unbind-key C-b
set -g prefix C-a
set -g base-index 1      # Start numbering windows at 1
set -g pane-base-index 1 # Start numbering panes at 1
# Ctrl-t or Ctrl-a t to create a new window.
bind -n C-t new-window
bind t new-window
# Ctrl-w or Ctrl-a w to close a window.
bind -n C-w kill-window
bind w kill-window
# Convenience methods
bind h split-window -h
bind v split-window -v
bind r source-file ~/.config/tmux/tmux.conf \; display "Config reloaded!"

# Theming
set -g pane-border-style "fg=#98c380"
set -g pane-active-border-style "fg=#56b6c2"
set -g message-style "fg=#000000 bg=#98c380"
#set -g status-style fg="#f0f0f0" bg="#0083be"
#set -g window-status-style fg="#f0f0f0" bg="#0083be"
#set -g window-status-current-style fg="#f0f0f0" bg="#0083be"

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'odedlaz/tmux-onedark-theme'
run '.config/tmux/plugins/tpm/tpm'

