format = "$username$hostname$directory$git_branch$git_status"
add_newline = false

[username]
format = "[$user]($style)[@](bold #98c379)"
show_always = true
style_user = "bold #98c379"
style_root = "inverted bold #98c379"

[hostname]
format = "[$hostname](bold #98c379) "
ssh_only = false

[directory]
truncation_length = 1
format = "[$path](bold #56b6c2) "

[git_branch]
format = "[$branch](bold #528bff)"

[git_status]
format = "[$modified](bold #528bff) "
modified = "*"
