format = "$username$hostname$directory$git_branch$git_status"
add_newline = false

[username]
format = "[$user]($style)[@](bold green)"
show_always = true
style_user = "bold green"
style_root = "inverted bold green"

[hostname]
format = "[$hostname](bold green) "
ssh_only = false

[directory]
truncation_length = 1
format = "[$path](bold cyan) "

[git_branch]
format = "[$branch](bold blue)"

[git_status]
format = "[$modified](bold blue) "
modified = "*"
